### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by MauriceHandwerker** [Votion-Development/VotionCad#1]
Hi I want to help but I would need a documentation. And is the version already usable so you can show a preview.

**Comment by babyharpsea** [comment]
Hello! If you want to help, just fork this repository, then edit and push the edited files to the repository. After doing that, you should see an option inside your repository to make a pull request to this repository to show changes here inside a pull request.

If you need images about the process, let me know and I'll provide them as soon as possible.

Hope I answered your question,
BHS.

**Comment by JamieGrimwood** [comment]
Hey, message me on discord and we can talk about contribution. Jamie_#0001
